import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,CheckCircle2,LocateFixed,MapPin,Navigation,Phone,ShieldAlert,ShieldCheck,Siren} from 'lucide-react';
const api=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
const labels={hospital:'Hospital',police:'Police station',shelter:'Shelter',garage:'Roadside / garage'};
const groupDefinitions=[{key:'hospital',title:'Nearest hospitals',kinds:['hospital']},{key:'police',title:'Nearest police stations',kinds:['police']},{key:'other',title:'Other nearby emergency places',kinds:['garage','shelter']}];
export default function EmergencyPage({initialLevel='standard',autoSearch=false,onAutoSearch=()=>{}}){
 const[level,setLevel]=useState(initialLevel),[location,setLocation]=useState(null),[places,setPlaces]=useState([]),[busy,setBusy]=useState(false),[status,setStatus]=useState('');
 const autoSearchStarted=useRef(false);
 const placeGroups=groupDefinitions.map(group=>({...group,places:places.filter(place=>group.kinds.includes(place.kind)).sort((a,b)=>(a.distanceKm??Infinity)-(b.distanceKm??Infinity))}));
 const nearestCallable=[...places].filter(place=>place.phone&&['hospital','police'].includes(place.kind)).sort((a,b)=>(a.distanceKm??Infinity)-(b.distanceKm??Infinity))[0];
 const findHelp=()=>{if(!navigator.geolocation){setStatus('Location is unavailable in this browser.');return;}setBusy(true);setStatus('Requesting location and searching nearby services…');
  // Only the traveler-triggered emergency action requests device coordinates and sends them to the SerpAPI-backed server route.
  navigator.geolocation.getCurrentPosition(async position=>{const coords={lat:position.coords.latitude,lng:position.coords.longitude};setLocation(coords);try{const response=await fetch(`${api}/emergencies`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...coords,level})});const data=await response.json();if(!response.ok)throw new Error(data.message||'Nearby search failed.');setPlaces(data.places||[]);setStatus(data.places?.length?'Nearby search complete. Listings are sorted by distance when map coordinates are available.':'No nearby listings were returned. Try again or call your local emergency number.');}catch(error){setPlaces([]);setStatus(`${error.message} Check that the backend and SerpAPI key are available.`);}finally{setBusy(false);}},error=>{setBusy(false);setStatus(error.code===1?'Location permission was not granted. Allow location access to search nearest services.':'Could not read your location. Check device location settings.');},{enableHighAccuracy:true,timeout:12000,maximumAge:0});};
 useEffect(()=>{if(autoSearch&&!autoSearchStarted.current){autoSearchStarted.current=true;findHelp();onAutoSearch();}},[autoSearch]);
 const openDirections=p=>{const to=p.gps?.latitude!=null&&p.gps?.longitude!=null?`${p.gps.latitude},${p.gps.longitude}`:p.name;window.open(`https://www.google.com/maps/dir/?api=1&origin=${location?.lat},${location?.lng}&destination=${encodeURIComponent(to)}`,'_blank','noopener,noreferrer');};
 return <div className="page-content secondary-page emergency-page"><div className="welcome-row"><div><div className="eyebrow"><ShieldCheck size={14}/> SAFETY CENTER</div><h1>Help is here when you need it.</h1><p className="welcome-sub">Choose the help you need. Your location is sent only after you request a nearby search.</p></div></div>
 <div className="emergency-levels"><button className={`emergency-level standard-level ${level==='standard'?'level-selected':''}`} onClick={()=>{setLevel('standard');setStatus('');setPlaces([])}}><div className="level-icon"><MapPin size={20}/></div><div><span>FOR NON-LIFE-THREATENING NEEDS</span><h2>I need some help</h2><p>Search hospitals, police stations, shelters, and roadside support.</p></div><CheckCircle2 size={18}/></button><button className={`emergency-level urgent-level ${level==='urgent'?'level-selected':''}`} onClick={()=>{setLevel('urgent');setStatus('');setPlaces([])}}><div className="level-icon"><Siren size={20}/></div><div><span>FOR IMMEDIATE DANGER</span><h2>Get urgent help</h2><p>Search emergency-focused categories near your current location.</p></div><CheckCircle2 size={18}/></button></div>
 {level==='urgent'&&<div className="urgent-explainer"><ShieldAlert size={18}/><div><strong>What urgent help does right now</strong><span>Searches nearby emergency rooms, police stations, crisis shelters, and roadside assistance with SerpAPI, then saves an urgent request. It does not call emergency services or notify your contacts.</span></div></div>}
 <section className="emergency-action"><div className="emergency-action-title"><div className={level==='urgent'?'urgent-action-icon':''}>{level==='urgent'?<ShieldAlert size={20}/>:<LocateFixed size={20}/>}</div><div><h2>{level==='urgent'?'Urgent nearby search':'Nearby support'}</h2><p>{level==='urgent'?'If you are in immediate danger, call your local emergency number now.':'Search live local listings around your current GPS location.'}</p></div></div><div className="location-box"><LocateFixed size={17}/><div><strong>Your current location</strong><span>{location?`${location.lat.toFixed(5)}, ${location.lng.toFixed(5)}`:'Not shared'}</span></div><span>Private until requested</span></div><button className={`primary-button emergency-submit ${level==='urgent'?'urgent-confirm':''}`} disabled={busy} onClick={findHelp}>{busy?'Searching nearby…':level==='urgent'?'Search urgent services':'Find nearby help'} <ArrowRight size={16}/></button>{status&&<p className="location-status" role="status">{status}</p>}<p className="emergency-disclaimer">SafeTravels is a prototype. It does not call, message, or stream your location to responders or emergency contacts. Call your local emergency number for immediate danger.</p></section>
 {level==='urgent'&&status&&!busy&&<section className="urgent-result-banner" role="status"><div className="urgent-result-symbol"><Siren size={23}/></div><div className="urgent-result-copy"><span>URGENT SEARCH UPDATE</span><h2>{places.length?'Nearby help is ready below':'We could not complete the nearby search'}</h2><p>{places.length?'Your search results are shown below, with the closest listings first in each group. SafeTravels has not contacted emergency services or your trusted contacts.':'Check your location permission or connection. If you are in immediate danger, call your local emergency number now.'}</p><small>Your location was used to search for nearby places; it was not sent to responders.</small></div>{nearestCallable&&<a className="urgent-call-place" href={`tel:${nearestCallable.phone}`}><Phone size={16}/><span>Call nearest listing<strong>{nearestCallable.name}</strong></span></a>}</section>}
 <section className="nearby-section"><div className="section-heading"><div><h2>Nearby help {places.length>0&&`(${places.length})`}</h2><p>{places.length?'Places are grouped by service; nearest listings appear first within each group.':'Results appear after you request a location search.'}</p></div>{places.length>0&&<button className="text-link" onClick={findHelp}><Navigation size={14}/> Refresh</button>}</div><div className="nearby-groups">{placeGroups.map(group=><section className="nearby-group" key={group.key}><div className="nearby-group-heading"><h3>{group.title}</h3><span>{group.places.length?`${group.places.length} found`:'No listings found'}</span></div><div className="nearby-list">{group.places.map((p,i)=><article className="nearby-row" key={`${p.kind}-${p.name}-${i}`}><div className="nearby-icon">{labels[p.kind]?.slice(0,1)||'+'}</div><div><strong>{p.name}</strong><span>{labels[p.kind]||p.kind}{p.distanceKm!=null?` · ${p.distanceKm.toFixed(1)} km`:''}{p.address?` · ${p.address}`:''}{p.rating?` · ★ ${p.rating}`:''}{p.openState?` · ${p.openState}`:''}</span></div><div className="nearby-actions">{p.phone&&<a href={`tel:${p.phone}`} aria-label={`Call ${p.name}`}><Phone size={14}/></a>}<button onClick={()=>openDirections(p)}><Navigation size={14}/>Directions</button></div></article>)}</div></section>)}</div></section><div className="help-note"><Phone size={15}/> If you’re in immediate danger, call the emergency number for your location.</div></div>;
}
