import React, { useState } from 'react';
import { ArrowRight, Bell, CalendarDays, Check, Circle, Compass, Hotel, MapPin, Plus, Shield, ShieldAlert, ShieldCheck, Siren, Sparkles } from 'lucide-react';

const screens=[
 {id:'dashboard',label:'Dashboard',icon:<Compass size={14}/>},
 {id:'planner',label:'Plan a trip',icon:<Sparkles size={14}/>},
 {id:'trips',label:'My trips',icon:<CalendarDays size={14}/>},
 {id:'todo',label:'To-do list',icon:<Check size={14}/>},
 {id:'emergency',label:'Emergency',icon:<ShieldAlert size={14}/>},
];
const photo='https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=700&q=80';
const hotelPhoto='https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=500&q=80';

function ActivityRow({time,title,detail,done=false}){return <div className="mock-activity"><span className={`mock-check ${done?'is-done':''}`}>{done&&<Check size={12}/>}</span><div><b>{title}</b><small>{detail}</small></div><time>{time}</time></div>}
function ScreenBody({screen,setScreen}){
 if(screen==='planner')return <div className="mock-content"><div className="mock-eyebrow">TRIP BUILDER · STEP 2 OF 3</div><h2>Choose a stay</h2><p className="mock-subtitle">Handpicked places in Kyoto</p><article className="mock-hotel"><img src={hotelPhoto} alt="Modern hotel"/><div><b>Riverlight Kyoto</b><span>★ 4.8 · 920 reviews</span><strong>$142 <small>/ night</small></strong></div></article><h3 className="mock-section-label">ACTIVITIES NEARBY</h3><div className="mock-mini-place"><span><MapPin size={14}/></span><div><b>Arashiyama Bamboo Grove</b><small>Nature · 2.4 km away</small></div><Check size={14}/></div><div className="mock-mini-place"><span><Compass size={14}/></span><div><b>Old Town Walking Tour</b><small>Culture · 1.2 km away</small></div><Circle size={14}/></div><button className="mock-blue-button">Build my schedule <ArrowRight size={14}/></button><p className="mock-note"><Sparkles size={12}/> Your selected places become a day-by-day plan.</p></div>;
 if(screen==='trips')return <div className="mock-content"><div className="mock-eyebrow">YOUR ADVENTURES</div><div className="mock-heading-row"><h2>My trips</h2><span className="mock-add"><Plus size={15}/></span></div><article className="mock-trip-card"><img src={photo} alt="Kyoto, Japan"/><div className="mock-trip-info"><span>UPCOMING</span><b>Kyoto, Japan</b><small><CalendarDays size={12}/> Oct 12 – Oct 18</small><em>Hotel + 8 activities</em></div></article><article className="mock-trip-card second"><div className="mock-trip-color"><MapPin size={21}/></div><div className="mock-trip-info"><span>COMPLETED</span><b>Lisbon, Portugal</b><small><CalendarDays size={12}/> Aug 03 – Aug 08</small><em>Hotel + 6 activities</em></div></article><div className="mock-tip"><Sparkles size={14}/><span><b>Pick up where you left off</b><small>Your saved itinerary is just a tap away.</small></span></div></div>;
 if(screen==='todo')return <div className="mock-content"><div className="mock-eyebrow">KYOTO · OCT 12–18</div><h2>Trip checklist</h2><p className="mock-subtitle">A little plan, a lot to look forward to.</p><div className="mock-progress-label"><span>3 of 8 done</span><b>38%</b></div><div className="mock-progress"><i/></div><h3 className="mock-section-label">MON, OCT 12</h3><ActivityRow time="9:30" title="Fushimi Inari Shrine" detail="Culture · 90 min" done/><ActivityRow time="12:30" title="Nishiki Market" detail="Food · 60 min" done/><ActivityRow time="3:30" title="Kiyomizu-dera Temple" detail="Culture · 90 min"/><ActivityRow time="6:00" title="Gion evening walk" detail="Neighborhood · 60 min"/><button className="mock-outline-button"><Plus size={14}/> Add an activity</button></div>;
 if(screen==='emergency')return <div className="mock-content mock-emergency-content"><div className="mock-emergency-icon"><Siren size={22}/></div><div className="mock-eyebrow red-eyebrow">SAFETY CENTER</div><h2>Nearby help, clearly.</h2><p className="mock-subtitle">Find local support near your current location.</p><button className="mock-sos-button"><ShieldAlert size={17}/> Get urgent help <ArrowRight size={15}/></button><div className="mock-location"><MapPin size={14}/><span>Current location<strong>Kyoto, Japan</strong></span><i>READY</i></div><h3 className="mock-section-label">NEAREST SUPPORT</h3><div className="mock-help-place"><span className="hospital-mark">+</span><div><b>Kyoto Central Hospital</b><small>Hospital · 0.8 km</small></div><span className="mock-call">CALL</span></div><div className="mock-help-place"><span className="police-mark"><Shield size={14}/></span><div><b>Higashiyama Police Box</b><small>Police · 1.1 km</small></div><span className="mock-call">CALL</span></div><div className="mock-safety-note">SafeTravels helps find nearby places. In a life-threatening emergency, call local emergency services.</div></div>;
 return <div className="mock-content"><div className="mock-welcome"><div><span className="mock-eyebrow">MONDAY, OCTOBER 12</span><h2>Good morning,<br/>Jamie <span>✳</span></h2></div><button className="mock-bell"><Bell size={16}/></button></div><button className="mock-sos-button dashboard-sos" onClick={()=>setScreen('emergency')}><span><Siren size={18}/></span><span><b>Emergency help</b><small>Nearby support is one tap away</small></span><ArrowRight size={16}/></button><article className="mock-destination"><img src={photo} alt="Kyoto street"/><div className="mock-destination-shade"/><div className="mock-destination-top"><span>YOUR NEXT ADVENTURE</span><span>OCT 12–18</span></div><div className="mock-destination-bottom"><span>Kyoto, Japan</span><small><Hotel size={12}/> Riverlight Kyoto · 8 activities</small></div></article><div className="mock-section-title"><h3>Today’s plan</h3><span>See all <ArrowRight size={12}/></span></div><ActivityRow time="9:30" title="Fushimi Inari Shrine" detail="Culture · 90 min" done/><ActivityRow time="12:30" title="Nishiki Market" detail="Food · 60 min"/><div className="mock-weather"><span>KYOTO WEATHER</span><b>22° <small>Clouds & sun</small></b></div></div>;
}

export default function MobilePreviewPage({embedded=false}){
 const[screen,setScreen]=useState('dashboard');
 return <section id="mobile-preview" className={`mobile-preview-section ${embedded?'mobile-preview-embedded':''}`}>
  <div className="mobile-preview-intro"><span className="eyebrow"><Sparkles size={14}/> MOBILE APP CONCEPT</span><h1>SafeTravels,<br/><span>in your pocket.</span></h1><p>Explore a visual preview of the app experience. Switch screens to see how planning, your trips, activities, and nearby emergency help fit a phone-sized layout.</p><div className="mobile-preview-pills"><span><Check size={13}/> Thumb-friendly controls</span><span><Check size={13}/> Clear, calm layouts</span><span><Check size={13}/> Help close at hand</span></div><div className="mobile-screen-picker"><span>PREVIEW A SCREEN</span><div>{screens.map(item=><button key={item.id} className={screen===item.id?'active':''} onClick={()=>setScreen(item.id)}>{item.icon}{item.label}</button>)}</div></div><small className="preview-disclaimer">Concept preview · buttons are for browsing these mock screens only</small></div>
  <div className="mobile-device-stage"><div className="device-halo"/><div className="mobile-device"><div className="mobile-device-inner"><div className="device-status"><span>9:41</span><i/><span>●●● ▰</span></div><div className="mock-appbar"><span className="mock-brand"><span><ShieldCheck size={16}/></span>safe<b>travels</b></span><span className="mock-safe-chip"><span/> READY TO GO</span></div><div className="mock-screen-scroll"><ScreenBody screen={screen} setScreen={setScreen}/></div><nav className="mock-bottom-nav">{screens.filter(item=>['dashboard','trips','todo','emergency'].includes(item.id)).map(item=><button key={item.id} className={screen===item.id?'selected':''} onClick={()=>setScreen(item.id)}>{item.icon}<span>{item.label==='Dashboard'?'Home':item.label==='To-do list'?'To-do':item.label==='Emergency'?'Help':item.label}</span></button>)}</nav></div><span className="device-button device-button-right"/><span className="device-button device-button-left"/></div><div className="mobile-device-caption"><span/><b>{screens.find(item=>item.id===screen)?.label}</b><span/></div></div>
 </section>;
}
