import React, { useState } from 'react';
import { ArrowLeft, Check, Circle, Plus, Trash2 } from 'lucide-react';
export default function TodoPage({ tasks, setTasks, onToggle, onDelete, onAdd }) {
 const [value,setValue]=useState(''); const [filter,setFilter]=useState('All');
 const add=()=>{if(!value.trim())return;const title=value.trim();if(onAdd)onAdd(title);else setTasks(ts=>[...ts,{id:Date.now(),time:'Anytime',title,meta:'Added to your trip',icon:'✦',done:false}]);setValue('')};
 const visible=tasks.filter(t=>filter==='All'||(filter==='Done'?t.done:!t.done));
 return <div className="page-content secondary-page"><div className="welcome-row"><div><div className="eyebrow">TRIP CHECKLIST</div><h1>Your to-do list.</h1><p className="welcome-sub">A small plan makes room for a big adventure.</p></div></div><section className="todo-panel"><div className="todo-summary"><div><strong>{tasks.filter(t=>t.done).length}<span> / {tasks.length}</span></strong><small>activities complete</small></div><div className="todo-progress"><i style={{width:`${tasks.length?tasks.filter(t=>t.done).length/tasks.length*100:0}%`}}/></div></div><div className="todo-filters">{['All','To do','Done'].map(f=><button key={f} className={filter===f?'selected-filter':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="todo-items">{visible.map(t=><div className={`todo-item ${t.done?'todo-complete':''}`} key={t.id}><button className={`task-check ${t.done?'checked':''}`} onClick={()=>onToggle?onToggle(t):setTasks(ts=>ts.map(x=>x.id===t.id?{...x,done:!x.done}:x))}>{t.done&&<Check size={13}/>}</button>{t.thumbnail?<img className="todo-activity-photo" src={t.thumbnail} alt=""/>:<span className="todo-emoji">{t.icon}</span>}<div><strong>{t.title}</strong><small>{t.time} · {t.meta}</small></div><button className="todo-remove" aria-label="Remove activity" onClick={()=>onDelete?onDelete(t):setTasks(ts=>ts.filter(x=>x.id!==t.id))}><Trash2 size={15}/></button></div>)}{!visible.length&&<div className="todo-empty"><Circle size={20}/>Nothing here yet. Add an activity below.</div>}</div><form className="todo-add" onSubmit={e=>{e.preventDefault();add()}}><input value={value} onChange={e=>setValue(e.target.value)} placeholder="Add a thing you’d like to do…"/><button className="primary-button" type="submit"><Plus size={16}/> Add activity</button></form></section><button className="back-link" onClick={()=>setFilter('All')}><ArrowLeft size={14}/> Showing all activities</button></div>;
}


